---
- hosts: server
  tasks:
  - debug: msg="The server Date is {{ ansible_date_time.date }} Time {{ ansible_date_time.hour}}:{{ansible_date_time.minute}}"
  - debug: msg="The OS is {{ansible_distribution}}"